generator_ckpt: wan_models/Wan2.1-T2V-1.3B/diffusion_pytorch_model.safetensors
generator_fsdp_wrap_strategy: size
real_score_fsdp_wrap_strategy: size
fake_score_fsdp_wrap_strategy: size
real_name: Wan2.1-T2V-1.3B
text_encoder_fsdp_wrap_strategy: size
ts_schedule: false
num_train_timestep: 1000
timestep_shift: 5.0
guidance_scale: 3.0
denoising_loss_type: flow
mixed_precision: true
seed: 0
wandb_host: WANDB_HOST
wandb_key: WANDB_KEY
wandb_entity: WANDB_ENTITY
wandb_project: self_forcing
sharding_strategy: hybrid_full
lr: 2.0e-06
lr_critic: 2.0e-06
beta1: 0.0
beta2: 0.999
beta1_critic: 0.0
beta2_critic: 0.999
weight_decay: 0.0
data_path: /checkpoints-fsx/beidchen-sandbox/video/Self-Forcing-Data/ode_pairs_lmdb_last_16k_extended_en_v3_shift5/data.mdb
batch_size: 1
sid_alpha: 1.0
ema_weight: 0.99
ema_start_step: 200
total_batch_size: 64
log_iters: 50
negative_prompt: '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走'
dfake_gen_update_ratio: 5
image_or_video_shape:
- 1
- 21
- 16
- 60
- 104
causal: false
trainer: ode
distribution_loss: ode
gradient_checkpointing: true
load_raw_video: false
model_kwargs:
  timestep_shift: 5.0